version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gas_station
    ports:
      - '5432:5432'
    volumes: 
      - ./pgData:/var/lib/postgresql
