# Generated by Django 4.0.4 on 2022-04-23 21:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=120)),
                ('maxCapacity', models.IntegerField()),
                ('currentFuel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FuelPump',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=120)),
                ('pricePerLiter', models.FloatField()),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tank')),
            ],
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantityLiters', models.FloatField()),
                ('tax', models.FloatField()),
                ('amount', models.FloatField()),
                ('fill_at', models.DateTimeField(auto_now_add=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.fuelpump')),
            ],
        ),
    ]
