# Generated by Django 4.0.4 on 2022-04-23 17:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2e978d47-3e86-4c50-ac21-805e07fcebc0'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=120)),
                ('maxCapacity', models.IntegerField()),
                ('currentFuel', models.IntegerField()),
            ],
        ),
    ]
