# Generated by Django 4.0.4 on 2022-04-23 17:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='id',
            field=models.UUIDField(default=uuid.UUID('14413426-963c-40f7-b439-7186d2d9f8ca'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='FuelPump',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b32b1bb8-5c1f-493c-ba25-f16a7c7f8147'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=120)),
                ('pricePerLiter', models.FloatField()),
                ('tankId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tank')),
            ],
        ),
    ]
