# Generated by Django 4.0.4 on 2022-04-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill',
            name='tax',
        ),
        migrations.AlterField(
            model_name='fill',
            name='quantityLiters',
            field=models.FloatField(auto_created=True, default=0, editable=False),
        ),
    ]
