# Generated by Django 4.0.4 on 2022-04-23 14:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3c34c9e9-411b-4910-9024-02b14e3dd3f3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='FuelPump',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6a69aff0-e017-4a6c-b3fe-31f066e3cee0'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=120)),
                ('pricePerLiter', models.FloatField()),
                ('tankId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tank')),
            ],
        ),
    ]
