# Generated by Django 4.0.4 on 2022-04-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_fill_tax_alter_fill_quantityliters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='quantityLiters',
            field=models.FloatField(auto_created=True, blank=True, default=0, editable=False),
        ),
    ]
