# Generated by Django 4.0.4 on 2022-04-24 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_fill_quantityliters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='fuelpump',
            name='pricePerLiter',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='tank',
            name='currentFuel',
            field=models.IntegerField(max_length=models.IntegerField(), validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
