# Generated by Django 4.0.4 on 2022-04-24 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_tank_currentfuel_alter_tank_maxcapacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='taxPaid',
            field=models.FloatField(auto_created=True, blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tank',
            name='currentFuel',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='tank',
            name='maxCapacity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
