# Generated by Django 4.0.4 on 2022-04-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_fill_taxpaid_alter_tank_currentfuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='fill_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
