# Generated by Django 4.0.4 on 2022-04-25 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_fill_fill_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='fill_at',
            field=models.DateField(default=datetime.date(2022, 4, 25)),
        ),
    ]
